name: screenshot-and-visitor

on:
  push:
    branches: [main, master]
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: read
  actions: read

env:
  BADGE_STYLE: 'for-the-badge'
  BADGE_COLOR: 'brightgreen'
  DATA_DIR: 'assets/db'
  SCREENSHOT_DIR: 'assets'

jobs:
  update-readme-and-visitor:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20.x'
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'false'

    steps:
      - name: 🔥 Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: 🔍 Check if sections are commented
        run: |
          # Перевіряємо чи закоментована секція скріншоту
          if grep -q "^[[:space:]]*<!--.*📸 Скріншот проекту" README.md || grep -q "^[[:space:]]*<!--.*📸 Latest Screenshot" README.md; then
            echo "📸 Screenshot section is commented out - skipping generation"
            echo "SCREENSHOT_SKIP=true" >> $GITHUB_ENV
          else
            echo "📸 Screenshot section is active - proceeding with generation"
            echo "SCREENSHOT_SKIP=false" >> $GITHUB_ENV
          fi

          # Перевіряємо чи закоментована секція статистики
          if grep -q "^[[:space:]]*<!--.*📊 Статистика GitHub" README.md || grep -q "^[[:space:]]*<!--.*📊 GitHub Statistics" README.md; then
            echo "📊 Stats section is commented out - skipping generation"
            echo "STATS_SKIP=true" >> $GITHUB_ENV
          else
            echo "📊 Stats section is active - proceeding with generation"
            echo "STATS_SKIP=false" >> $GITHUB_ENV
          fi

      - name: 🚀 Initialize workflow
        run: |
          DATA_DIR="$DATA_DIR"
          SCREENSHOT_DIR="$SCREENSHOT_DIR"
          mkdir -p "$DATA_DIR" "$SCREENSHOT_DIR"

          # Зберігаємо початковий вміст README
          cp README.md README_backup.md

          # Отримуємо вміст до і після автогенерованої секції
          awk '/<!-- AUTOGEN:STATS -->/{exit} {print}' README.md > README_before.tmp
          awk '/<!-- END:AUTOGEN -->/{found=1; next} found{print}' README.md > README_after.tmp

          # Створюємо тимчасовий README без автогенерованого вмісту
          {
            cat README_before.tmp
            echo "<!-- AUTOGEN:STATS -->"
            echo "🔄 Оновлення статистики..."
            echo "<!-- END:AUTOGEN -->"
            cat README_after.tmp
          } > README.md

          echo "🚀 Workflow initialized, README prepared for updates"

      - name: 📊 Collect all statistics
        run: |
          # Створюємо badges для статистики (без лайків)
          REPO_NAME="${{ github.repository }}"
          REPO_OWNER=$(echo "$REPO_NAME" | cut -d'/' -f1)
          REPO_REPO=$(echo "$REPO_NAME" | cut -d'/' -f2)
          
          # Статистика переглядів
          echo '{"schemaVersion":1,"label":"📊 Views","message":"","color":"brightgreen","style":"for-the-badge"}' > $DATA_DIR/visitors-badge.json
          
          # Розмір репозиторію
          echo '{"schemaVersion":1,"label":"📦 Size","message":"","color":"brightgreen","style":"for-the-badge"}' > $DATA_DIR/repo-size.json
          
          # Ліцензія
          echo '{"schemaVersion":1,"label":"📄 License","message":"MIT","color":"brightgreen","style":"for-the-badge"}' > $DATA_DIR/repo-license.json
          
          # Downloads badge (якщо є релізи)
          if [ -f "$DATA_DIR/downloads-badge.json" ]; then
            echo "Downloads badge already exists"
          else
            echo '{"schemaVersion":1,"label":"⬇️ Downloads","message":"0","color":"brightgreen","style":"for-the-badge"}' > $DATA_DIR/downloads-badge.json
          fi

      - name: 🖥 Setup Node.js and dependencies
        run: |
          if [ "$SCREENSHOT_SKIP" = "true" ]; then
            echo "⏭️ Skipping Node.js setup - screenshot generation disabled"
            exit 0
          fi
          
          # Встановлюємо Node.js
          curl -fsSL https://deb.nodesource.com/setup_$NODE_VERSION | sudo -E bash -
          sudo apt-get install -y nodejs
          
          # Перевіряємо версію
          node --version
          npm --version

      - name: 📸 Generate screenshot from GitHub Pages
        run: |
          if [ "$SCREENSHOT_SKIP" = "true" ]; then
            echo "⏭️ Screenshot generation skipped - section is commented out"
            echo "SCREENSHOT_CREATED=false" >> $GITHUB_ENV
            exit 0
          fi
          
          # Спробуємо зробити скріншот GitHub Pages
          GITHUB_PAGES_URL="https://$REPO_OWNER.github.io/$REPO_REPO"
          
          # Перевіряємо чи сторінка існує
          if curl --output /dev/null --silent --head --fail "$GITHUB_PAGES_URL"; then
            echo "📸 GitHub Pages found, generating screenshot..."
            
            # Встановлюємо Puppeteer для скріншотів
            npm install puppeteer-core chromium --no-save
            
            # Створюємо скрипт для скріншоту
            cat > screenshot.js << 'EOF'
            const puppeteer = require('puppeteer-core');
            const chromium = require('chromium');
            
            (async () => {
              const browser = await puppeteer.launch({
                executablePath: chromium.path,
                args: ['--no-sandbox', '--disable-setuid-sandbox']
              });
              
              const page = await browser.newPage();
              await page.setViewport({ width: 1280, height: 720 });
              
              try {
                await page.goto('$GITHUB_PAGES_URL', { waitUntil: 'networkidle2', timeout: 30000 });
                await page.screenshot({ path: '$SCREENSHOT_DIR/screenshot.png', fullPage: false });
                console.log('✅ Screenshot created successfully');
              } catch (error) {
                console.log('❌ Screenshot failed:', error.message);
                process.exit(1);
              } finally {
                await browser.close();
              }
            })();
            EOF
            
            # Запускаємо скрипт
            node screenshot.js
            echo "SCREENSHOT_CREATED=true" >> $GITHUB_ENV
          else
            echo "🌐 GitHub Pages not available, skipping screenshot"
            echo "SCREENSHOT_CREATED=false" >> $GITHUB_ENV
          fi

      - name: 📝 Update README with all content
        run: |
          REPO_URL="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}"
          
          # Відновлюємо оригінальний README
          mv README_backup.md README.md

          # Отримуємо вміст до і після автогенерованої секції
          awk '/<!-- AUTOGEN:STATS -->/{exit} {print}' README.md > README_before.tmp
          awk '/<!-- END:AUTOGEN -->/{found=1; next} found{print}' README.md > README_after.tmp

          {
            cat README_before.tmp
            echo "<!-- AUTOGEN:STATS -->"
            
            # Додаємо технологічні бейджі тільки якщо секція не закоментована
            if [ "$STATS_SKIP" = "false" ]; then
              echo ""
              echo "## 📊 Статистика GitHub :"
              echo ""
              echo "[![📊 Views](https://img.shields.io/endpoint?url=$REPO_URL/$DATA_DIR/visitors-badge.json)](https://github.com/${{ github.repository }}/graphs/traffic)"
              echo "[![⭐ Stars](https://img.shields.io/github/stars/${{ github.repository }}?style=for-the-badge)](https://github.com/${{ github.repository }}/stargazers)"
              echo "[![📦 Size](https://img.shields.io/endpoint?url=$REPO_URL/$DATA_DIR/repo-size.json)](https://github.com/${{ github.repository }})"
              echo "[![📄 License](https://img.shields.io/endpoint?url=$REPO_URL/$DATA_DIR/repo-license.json)](https://github.com/${{ github.repository }}/blob/main/LICENSE)"
              echo "[![⬇️ Downloads](https://img.shields.io/endpoint?url=$REPO_URL/$DATA_DIR/downloads-badge.json)](https://github.com/${{ github.repository }}/releases)"
            else
              echo "<!-- 📊 Статистика GitHub закоментована -->"
            fi
            
            # Додаємо скріншот тільки якщо секція не закоментована
            if [ "$SCREENSHOT_SKIP" = "false" ] && [ "$SCREENSHOT_CREATED" = "true" ] && [ -f "$SCREENSHOT_DIR/screenshot.png" ]; then
              SCREENSHOT_SIZE=$(stat -f%z "$SCREENSHOT_DIR/screenshot.png" 2>/dev/null || stat -c%s "$SCREENSHOT_DIR/screenshot.png" 2>/dev/null || echo "0")
              if [ "$SCREENSHOT_SIZE" -gt 0 ]; then
                echo ""
                echo "## 📸 Скріншот проекту"
                echo "![Project Screenshot](./$SCREENSHOT_DIR/screenshot.png)"
              fi
            else
              echo "<!-- 📸 Скріншот проекту закоментований -->"
            fi
            
            echo "<!-- END:AUTOGEN -->"
            cat README_after.tmp
          } > README.md

          rm -f README_before.tmp README_after.tmp
          echo "✅ README updated with all content"

      - name: 📤 Commit and deploy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .

          COMMIT_MSG="📊 Auto-update: visitors"
          if [ "$SCREENSHOT_CREATED" = "true" ]; then
            COMMIT_MSG="$COMMIT_MSG and screenshot"
          fi

          git commit -m "$COMMIT_MSG" || exit 0
          git pull --rebase https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          echo "✅ All updates completed successfully"